# -*- coding: utf-8 -*-
"""CREDIT CARD FRAUD  DETECTION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVymkpivD-2P31RXdazxuEp-9Kv60R7G

Import Libraries
"""

import pandas as pd
import numpy as np

"""Loading Dataset"""

data = pd.read_csv("/content/fraudTest.csv")

data.shape

data.columns

"""Remove extra spaces from column names"""

data.columns = data.columns.str.strip()

data.head()

"""Checking Dataset Information"""

print(data.info())

print(data.isnull().sum())

"""Fraud and Genuine Transaction Count"""

fraud_count = data['is_fraud'].value_counts()

print("\nTransaction Count:")
print(fraud_count)

print("\nExplanation:")
print("0 = Genuine Transaction")
print("1 = Fraudulent Transaction")

"""Features and Targets"""

X= data.drop(columns=[
    'Unnamed: 0', 'is_fraud', 'merchant', 'category', 'first', 'last',
    'gender', 'street', 'city', 'state', 'job', 'dob', 'trans_num'
], axis=1)
y = data['is_fraud']

"""Splitting the dataset"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train['trans_date_trans_time'] = pd.to_datetime(X_train['trans_date_trans_time']).astype(int) / 10**9

"""Creating the Model"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=5000)

"""Training the Model"""

model.fit(X_train, y_train)

X_test['trans_date_trans_time'] = pd.to_datetime(X_test['trans_date_trans_time']).astype(int) / 10**9

"""Predicting Tranactions"""

y_pred = model.predict(X_test)

"""Checking the Accuracy"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:")
print(accuracy)

from sklearn.metrics import confusion_matrix

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

"""Graph Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(3,3))
sns.countplot(x='is_fraud', data=data)
plt.title("Fraud vs Genuine Transactions")
plt.xlabel("Transaction Type")
plt.ylabel("Count")
plt.xticks([0,1], ['Genuine', 'Fraud'])
plt.show()